version: "2"
services:

  westudy:
      build: .
      ports:
        - "8088:8088"
      links:
        - "mariadb"
        - "redis"
      volumes:
        - $HOME/code/go:/go
      tty: true  

  mariadb:
    image: mariadb:10.2
    volumes:
      - ./data:/var/lib/mysql
    container_name: mariadb
    ports:
      - "3311:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    restart: always

  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: westudy-goin-pma
    depends_on:
      - mariadb
    links:
      - mariadb:db
    ports:
      - "2344:80"

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes --requirepass "123456"
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data